<?php
namespace app\Amanmin\controller;

use think\Controller;

class Base extends Controller
{
   protected function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       if(!session('?admin.id')){
           $this->redirect('/amanmin/login');

       }

       $sys=cache('sysinfo');
       if(!$sys){
           $sys=model('sys')->getSysInfo();
           cache('sysinfo',$sys,1800);
       }
       $this->assign('sysinfo',$sys);

   }

}
