<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 2019/10/3
 * Time: 15:09
 */

namespace app\home\controller;


use app\home\model\Safelog;
use think\Controller;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $list=['index','rank','down','links','tools','notice','info'];
        $controller=strtolower(request()->controller());
        if(!session('?user.id')){
            if(!in_array($controller,$list)){
                $this->redirect('/login');
            }
        }

        $result=amanCheck();
        if($result){
            $warn=new Safelog();
            $warn->addLog($result['type'],$result['info']);

        }

        $sys=cache('sysinfo');
        if(!$sys){
            $sys=model('sys')->getSysInfo();
            cache('sysinfo',$sys,1800);
        }
        $this->assign('controller',$controller);
        $this->assign('sysinfo',$sys);

    }
}